Controllers/VkrController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using FinalWork_BD_Test.Data;
using FinalWork_BD_Test.Data.ConfigModels;
using FinalWork_BD_Test.Data.Models;
using FinalWork_BD_Test.Data.Models.Data;
using FinalWork_BD_Test.Data.Models.Profiles;
using FinalWork_BD_Test.Documents;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace FinalWork_BD_Test.Controllers
{
    [Authorize]
    public class VkrController : Controller
    {
        private ApplicationDbContext _context;
        private UserManager<User> _userManager;
        private RoleManager<Role> _roleManager;
        private IOptions<DocumentsConfig> _documentsConfig;

        public VkrController(ApplicationDbContext c, UserManager<User> u, RoleManager<Role> rm, IOptions<DocumentsConfig> documentsConfig)
        {
            _roleManager = rm;
            _context = c;
            _userManager = u;
            _documentsConfig = documentsConfig;
        }

        /// <summary>
        /// Общие сведения о ВКР
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Common()
        {
            var currentUser = _userManager.GetUserAsync(this.User).Result;
            
            var vkr = _context.VKRs
                .Include(t => t.StudentUP)
                .Include(t => t.SupervisorUP)
                .Include(t => t.Degree)
                .Include(t => t.Topic)
                .Include(t => t.Semester)
                .Include(t => t.ReviewerUP)
                .FirstOrDefault(t => t.StudentUP.User == currentUser && t.UpdatedByObj == null);

             
            ViewData["ActiveView"] = "Common";
            ViewData["CurrentYear"] = (ulong) DateTime.Now.Year;
            
            if (vkr != null)
            {
                ViewData["UserProfile.Id"] = VKR.GetSupervisorList(_context, _userManager, vkr.SupervisorUP);
                
                if (vkr.Semester == null)
                    vkr.Semester = _context.Semesters.First();
                
                ViewData["Semester.Id"] = new SelectList(_context.Semesters.AsEnumerable(), 
                    "Id", "Name", vkr.Semester.Id);
                
                ViewData["Degree.Id"] = new SelectList(_context.Degrees.AsEnumerable(), 
                    "Id", "Name", vkr.DegreeId);
                
                ViewData["ReviewerId"] = ReviewerProfile.GetReviewerList(_context, vkr.ReviewerUP);

                return View(vkr);
            }
            
            ViewData["Degree.Id"] = new SelectList(_context.Degrees.AsEnumerable(), 
                "Id", "Name");
            
            ViewData["Semester.Id"] = new SelectList(_context.Semesters.AsEnumerable(), 
                "Id", "Name", Semester.CurrentSemester(_context).Id);
            
            ViewData["UserProfile.Id"] = VKR.GetSupervisorList(_context, _userManager);
            
            ViewData["ReviewerId"] = ReviewerProfile.GetReviewerList(_context);
            
            return View(new VKR { Year = (ulong)DateTime.Now.Year });
        }


        /// <summary>
        /// Регистрация/редактирование ВКР
        /// </summary>
        /// <param name="topic"></param>
        /// <param name="userProfile"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Common([FromForm] Topic topic, [FromForm] UserProfile userProfile, [FromForm] ulong year, 
            [FromForm] Semester semester, [FromForm] Guid? reviewerId, [FromForm] Degree degree)
        {
            var currentUser = _userManager.GetUserAsync(this.User).Result;

            topic.CreatedDate = DateTime.Now;
            topic.Author = currentUser;

            _context.Entry(currentUser).Collection(cu => cu.UserProfiles).Load();
            _context.Entry(currentUser).Collection(cu => cu.StudentProfiles).Load();

            //var superVisorLp = userProfile.User.LecturerProfiles.FirstOrDefault(l => l.UpdatedByObj == null);
            var superVisorLp = _context.LecturerProfiles.FirstOrDefault(l =>
                l.User.UserProfiles.FirstOrDefault(u => u.UpdatedByObj == null).Id == userProfile.Id);

            var prvVkr = _context.VKRs
                .Include(t => t.Topic)
                .FirstOrDefault(t => t.UpdatedByObj == null && t.StudentUP.User == currentUser);

            if (_context.Degrees.FirstOrDefault(d => d.Id == degree.Id)?.Name != "Магистр")
                reviewerId = null;

            // GEC Link
            var student = currentUser.StudentProfiles.FirstOrDefault(up => up.UpdatedBy == null);
            var gec = _context.GECs.FirstOrDefault(gec => gec.Group == student.Group);

            var vkr = new VKR()
            {
                Topic = topic,
                CreatedDate = DateTime.Now,
                SupervisorUPId = userProfile.Id,
                SupervisorLPId = superVisorLp?.Id,
                StudentUP = currentUser.UserProfiles.FirstOrDefault(t => t.UpdatedByObj == null),
                Year = year,
                SemesterId = semester.Id,
                ReviewerUPId = reviewerId,
                DegreeId = degree.Id,
                Gec = gec
            };
            
            if (prvVkr != null)
                if (VKR.EqualsVkr(prvVkr, vkr))
                    return RedirectToAction();

            _context.VKRs.Add(vkr);

            if (prvVkr != null)
                prvVkr.UpdatedByObj = vkr;

            _context.SaveChanges();

            return RedirectToAction();
        }
        
        public IActionResult DocumentsForms()
        {
            ViewData["ActiveView"] = "DocumentsForms";
            ViewData["DocumentsFormsDictionary"] = new Dictionary<string, string>
            {
                //Название шаблона, имя файла шаблона
                { "Приложение 1.Титульный лист", "Приложение_1.Титульный_лист"},
                { "Приложение 2.Бланк задания на ВКР", "Приложение_2.Бланк_задания_на_ВКР"},
                { "Приложение 3.Бланк акта предварительной защиты ВКР", "Приложение_3.Бланк_акта_предварительной_защиты_ВКР"},
                { "Приложение 4.Бланк отзыва руководителя на ВКР", "Приложение_4.Бланк_отзыва_руководителя_на_ВКР"},
                { "Приложение 5.Бланк рецензии на ВКР", "Приложение_5.Бланк_рецензии_на_ВКР"},
                { "Согласие размещение текста ВКР в ЭБС КНИТУ-КАИ", "Согласие_размещение_текста_ВКР_в_ЭБС_КНИТУ-КАИ"}
            };
            return View();
        }
        public IActionResult MainDocuments()
        {
            ViewData["ActiveView"] = "MainDocuments";
            var currentUser = _userManager.GetUserAsync(this.User).Result;
            VKR vkr = _context.VKRs
                .Include(vkr => vkr.StudentUP)
                .Include(vkr => vkr.UploadableDocuments).ThenInclude(ud => ud.LocalizedStatus)
                .FirstOrDefault(vkr => vkr.StudentUP.User == currentUser && vkr.UpdatedBy == null);

            var documentsList = new List<string>
            {
                "Полностью собранная ВКР",
                "Отзыв научного руководителя",
            };

            var documents = new Dictionary<string, UploadableDocument>();

            foreach (var document in documentsList)
            {
                documents.Add(document,
                    vkr?.UploadableDocuments.FirstOrDefault(ud => ud.Type == document && ud.UpdatedByObj == null));
            }

            ViewData["MainDocumentsDictionary"] = documents;
            

            return View();
        }

        public FileResult DownloadMainDocument(Guid id)
        {
            var currentUser = _userManager.GetUserAsync(this.User).Result;
            var document = _context.UploadableDocuments.FirstOrDefault(ud => ud.Id == id);

            var fileResult = new PhysicalFileResult( document.Path, "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
            {
                FileDownloadName = $"{document.OriginalName}"
            };

            return fileResult;
        }

        public IActionResult OtherDocuments()
        {
            ViewData["ActiveView"] = "OtherDocuments";
            return View();
        }

        public IActionResult BuildVkr()
        {
            ViewData["ActiveView"] = "BuildVkr";
            return View();
        }

        public IActionResult Documents()
        {
            ViewData["ActiveView"] = "Documents";
            return View();
        }

        public FileResult Generate(string templateName)
        {
            var currentUser = _userManager.GetUserAsync(this.User).Result;
            return Generator.Generate(templateName, _context, currentUser, _documentsConfig);
        }

        public IActionResult UploadDocument(IFormFile uploadedDocument, string type)
        {
            var currentUser = _userManager.GetUserAsync(this.User).Result;
            var currentVkr = _context.VKRs
                .Include(vkr => vkr.UploadableDocuments)
                .FirstOrDefault(vkr =>
                vkr.IsArchived == false && vkr.UpdatedBy == null && vkr.StudentUP.User == currentUser);

            if (uploadedDocument != null)
            {
                var previousDocument = currentVkr.UploadableDocuments.FirstOrDefault(ud => ud.Type == type);

                UploadableDocument uploadableDocument = new UploadableDocument
                {
                    Type = type,
                    OriginalName = uploadedDocument.FileName, 
                    Path = "", 
                    Length = uploadedDocument.Length, 
                    Status = DocumentStatus.Verification, 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - АСУ ВКР</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-select/dist/css/bootstrap-select.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">АСУ ВКР</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Начальная страница</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vkr" asp-action="Common">ВКР</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Faq">FAQ</a>
                            </li>

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Panel</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>