Controllers/GecController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalWork_BD_Test.Data;
using FinalWork_BD_Test.Data.Models;
using FinalWork_BD_Test.Data.Models.Intermidate;
using FinalWork_BD_Test.Data.Models.Profiles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FinalWork_BD_Test.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GecController : Controller
    {
        private ApplicationDbContext _context;
        private UserManager<User> _userManager;

        public GecController(ApplicationDbContext c, UserManager<User> u)
        {
            _context = c;
            _userManager = u;
        }

        [HttpGet]
        public IActionResult GecMemberProfile()
        {
            ViewData["AcademicDegreeId"] = new SelectList(_context.AcademicDegrees.AsNoTracking().AsEnumerable(), "Id", "Name");//.Append(new SelectListItem("Отсутствует", "null", true));
            ViewData["AcademicTitleId"] = new SelectList(_context.AcademicTitles.AsNoTracking().AsEnumerable(), "Id", "Name");//.Append(new SelectListItem("Отсутствует", "null", true));

            return View();
        }

        [HttpPost]
        public IActionResult GecMemberProfile(GecMemberProfile profile)
        {
            profile.UpdatedByObj = null;
            profile.CreatedDate = DateTime.Now;

            _context.GecMemberProfiles.Add(profile);
            _context.SaveChanges();

            return View();
        }

        //[HttpGet]
        //public IActionResult Gec()
        //{
        //    ViewData["MembersId"] = new SelectList(_context.GecMemberProfiles.Where(mp => mp.UpdatedByObj == null), "Id", "FirstNameIP");
        //    ViewData["EducationFormId"] = new SelectList(_context.EducationForms, "Id", "Name");

        //    return View();
        //}

        [HttpGet]
        public IActionResult Gec(Guid gecId)
        {
            GEC gec = _context.GECs.FirstOrDefault(g => g.Id == gecId);
            _context.GecMemberProfiles.Load();
            _context.GecMemberIntermediates.Load();

            SelectList MembersProfiles = new SelectList(_context.GecMemberProfiles.Where(mp => mp.UpdatedByObj == null), "Id", "FirstNameIP");
            ViewData["EducationFormId"] = new SelectList(_context.EducationForms, "Id", "Name");

            if (gec != null)
            {
                if (gec.Members != null)
                    foreach (var member in gec.Members)
                    {
                        var memberListItem = MembersProfiles.FirstOrDefault(mp => mp.Value == member.MemberProfileId.ToString());
                        if (memberListItem != null)
                            memberListItem.Selected = true;
                    }
            }

            ViewData["MembersId"] = MembersProfiles;

            //return View("Gec", gec);
            return View(gec);
        }

        [HttpPost]
        public IActionResult GEC(GEC gec, ICollection<Guid> membersid)
        {
            gec.UpdatedByObj = null;
            gec.CreatedDate = DateTime.Now;

            //TEMP
            gec.Chief = _context.GecMemberProfiles.First(mp => mp.Id == gec.Chief.Id);
            gec.Deputy = _context.GecMemberProfiles.First(mp => mp.Id == gec.Deputy.Id);

            _context.GECs.Add(gec);


            foreach (Guid member in membersid)
            {
                var memberIntermidiate = new GecMemberIntermediate { GecId = gec.Id, MemberProfileId = member };
                _context.GecMemberIntermediates.Add(memberIntermidiate);
                gec.Members.Add(memberIntermidiate);
            }

            _context.SaveChanges();

            return RedirectToAction();
        }
    }
}

Areas/Admin/Views/Shared/_AdminNavBar.cshtml
@using FinalWork_BD_Test.Areas.Admin.Views
<ul class="nav nav-pills flex-column" xmlns="http://www.w3.org/1999/html">
    <li class="nav-item">
        <a class="nav-link @AdminNavBar.IndexNavClass(ViewContext)" asp-area="Admin" asp-controller="Home" 
           asp-action="Index">Начальная страница</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @AdminNavBar.AllUsersNavClass(ViewContext) @AdminNavBar.FindUsersNavClass(ViewContext)" 
           data-toggle="collapse" href="#collapseUsers" role="button" aria-expanded="false" aria-controls="collapseUsers">
            Пользователи
        </a>
        <div class="collapse" id="collapseUsers">
            <div class="card card-body">
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a class="nav-link @AdminNavBar.AllUsersNavClass(ViewContext)" asp-area="Admin" 
                           asp-controller="Home" asp-action="AllUsers">Все пользователи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link @AdminNavBar.FindUsersNavClass(ViewContext)" asp-area="Admin" 
                           asp-controller="Home" asp-action="FindUsers">Найти пользователя</a>
                    </li>
                </ul>
            </div>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link @AdminNavBar.AllRolesNavClass(ViewContext)" asp-area="Admin" asp-controller="Home" 
           asp-action="AllRoles">Роли</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @AdminNavBar.AllReviewersNavClass(ViewContext) @AdminNavBar.FindReviewerNavClass(ViewContext)" 
           data-toggle="collapse" href="#collapseReviewers" role="button" aria-expanded="false" aria-controls="collapseReviewers">
            Рецензенты
        </a>
        <div class="collapse" id="collapseReviewers">
            <div class="card card-body">
                <ul class="nav nav-pills flex-column">        
                    <li class="nav-item">
                        <a class="nav-link @AdminNavBar.AllReviewersNavClass(ViewContext)" asp-area="Admin" asp-controller="Home"
                           asp-action="AllReviewers">Все рецензенты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link @AdminNavBar.FindReviewerNavClass(ViewContext)" asp-area="Admin" asp-controller="Home"
                           asp-action="FindReviewer">Найти рецензента</a>
                    </li>
                </ul>
            </div>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link @AdminNavBar.AllVkrsNavClass(ViewContext)" asp-area="Admin" asp-controller="Home" 
           asp-action="AllVkrs">Список ВКР</a>
    </li>
    <li class="nav-item">
        <a class="nav-link @AdminNavBar.GecNavClass(ViewContext)" asp-area="Admin" asp-controller="Gec" 
           asp-action="Index">ГЭК</a>
    </li>
</ul>

Areas/Admin/Views/Shared/_Layout.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Admin Panel";
}

<h2>Admin panel</h2>

<div>
    <div class="row">
        <div class="col-md-3">
            <partial name="_AdminNavBar" />
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>

@section Scripts {
    @RenderSection("Scripts", required: false)
}

Areas/Admin/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}